version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install
          command: |
            sudo apt-get install texlive-base
            sudo apt-get install texlive
            sudo apt-get install texlive-latex-extra
            sudo apt-get install texlive-latex-recommended
            sudo apt-get install texlive-fonts-recommended
            sudo apt-get install texlive-latex-extra
            sudo apt-get install texlive-science
            sudo apt-get install lmodern
            sudo apt-get install texlive-lang-french
            sudo pip3 install numpy
            sudo pip3 install scipy
            sudo pip3 install matplotlib
            sudo pip3 install jupyter
      - run:
          name: Build and test - global
          command: ./.circleci/run_docker_linux.sh

